In [2]:
import numpy as np # linear algebra

# Solving Linear System of Equation

Let's consider a business scenario where a company is managing its inventory of products. The company sells three types of products: A, B, and C. They receive weekly shipments of these products from three different suppliers: Supplier X, Supplier Y, and Supplier Z. The goal is to keep track of the inventory levels and manage the orders from different suppliers to maintain optimal stock levels and minimize costs.

**Weekly shipments from each supplier:**

Supplier X: 20 units of Product A, 15 units of Product B, 10 units of Product C

Supplier Y: 10 units of Product A, 15 units of Product B, 25 units of Product C

Supplier Z: 25 units of Product A, 30 units of Product B, 20 units of Product C

**Weekly demand for each product:**

Product A: 35 units

Product B: 20 units

Product C: 15 units

**Objective:**

To find out how much inventory of each product should be ordered from each supplier to meet the weekly demand and minimize the total cost of orders.

In [69]:
# Given data
A = np.array([[10, 15, 10], [15, 5, 15], [35, 10, 10]])
demand = np.array([5500, 6000, 9500])

# Solving the system of linear equations
quantities_ordered = np.linalg.solve(A, demand)

# Round off the quantities to whole numbers (since you can't order a fraction of a product)
quantities_ordered = np.round(quantities_ordered).astype(int)

print("Quantities ordered from each supplier:")
print(f"Supplier X: {quantities_ordered[0]} units")
print(f"Supplier Y: {quantities_ordered[1]} units")
print(f"Supplier Z: {quantities_ordered[2]} units")

Quantities ordered from each supplier:
Supplier X: 186 units
Supplier Y: 129 units
Supplier Z: 171 units


Imagine you own a bakery that produces two types of products: Cakes and Cookies. You source the ingredients from two different suppliers: Supplier A and Supplier B. Each supplier provides you with details about the cost of ingredients required to produce one unit of Cakes and one unit of Cookies.

Given the data from Supplier A and Supplier B, you want to determine the optimal pricing strategy for Cakes and Cookies. The goal is to maximize the total revenue while considering the cost of ingredients from each supplier.

**Suppose the following information is available:**

Supplier A provides ingredients for Cakes at 100 per unit and ingredients for Cookies at 30 per unit.

Supplier B provides ingredients for Cakes at 10 per unit and ingredients for Cookies at 80 per unit.

The bakery has a weekly budget constraint, where the total cost of ingredients from Supplier A should not exceed 6000, and the total cost of ingredients from Supplier B should not exceed 4000.

In [70]:
# Coefficients matrix
coefficients = np.array([[90, 30], [10, 80]])

# Constants matrix
constants = np.array([6000, 4000])

# Solve the linear system
solution = np.linalg.solve(coefficients, constants)

# Extract the individual solutions
unit_price_A, unit_price_B = solution

print(f"Unit price of Cakes: ${unit_price_A}")
print(f"Unit price of Cookies: ${unit_price_B}")

Unit price of Cakes: $52.17391304347826
Unit price of Cookies: $43.47826086956522


# Matrix/Vector Addition

Imagine you are a regional manager responsible for overseeing multiple stores in your area. You have three stores under your management: Store 1, Store 2, and Store 3. Each store provides you with their weekly sales data for three products: Product A, Product B, and Product C.

Given the weekly sales data from each store, you need to consolidate the information into a single sales report to get an overview of the overall performance in the region.

The provided code performs matrix addition to consolidate the weekly sales data from all three stores into a single matrix called consolidated_sales.

**Suppose the following is the sales data provided by each store for the week:**

Store 1 sales: 50 units of Product A, 30 units of Product B, and 20 units of Product C.

Store 2 sales: 40 units of Product A, 20 units of Product B, and 15 units of Product C.

Store 3 sales: 60 units of Product A, 40 units of Product B, and 30 units of Product C.

In [4]:
# Given data - Sales matrices for each store
store_1_sales = np.array([[50, 30, 20]])
store_2_sales = np.array([[40, 20, 15]])
store_3_sales = np.array([[60, 40, 30]])

# Perform matrix addition to consolidate weekly sales
consolidated_sales = store_1_sales + store_2_sales + store_3_sales

print("Consolidated Weekly Sales Matrix:")
print(consolidated_sales)

Consolidated Weekly Sales Matrix:
[[150  90  65]]


# Matrix/Vector Subtraction

Imagine you are a sales manager responsible for overseeing the performance of two retail stores, Store A and Store B, located in different neighborhoods. As part of your regular analysis, you collect data on the weekly sales of three popular products: Product X, Product Y, and Product Z.

Given the weekly sales data from both stores, you want to compare the sales performance of each store for the three products. To do this, you use matrix subtraction to find the differences in weekly sales between Store A and Store B.

**Suppose you have the following sales data for the week:**

Store A sales: 50 units of Product X, 30 units of Product Y, and 20 units of Product Z.

Store B sales: 40 units of Product X, 20 units of Product Y, and 15 units of Product Z.

In [52]:
# Sales matrices for Store A and Store B
store_A_sales = np.array([[50, 30, 20]])
store_B_sales = np.array([[40, 20, 15]])

# Perform matrix subtraction to find the difference in weekly sales
sales_difference = store_A_sales - store_B_sales

print("Matrix representing the difference in weekly sales between Store A and Store B:")
print(sales_difference)

Matrix representing the difference in weekly sales between Store A and Store B:
[[10 10  5]]


# Scalar Addition/Subtraction to Matrix

Imagine you are a meteorologist working with a team to analyze temperature data from different weather stations across the world. The temperature data is recorded in both Celsius and Fahrenheit for accuracy and convenience.

Your team receives temperature data for a particular day in two separate matrices. The first matrix holds the temperature readings in Celsius, and the second matrix holds the corresponding temperature readings in Fahrenheit. However, the temperature data in both matrices needs to be adjusted to account for a sudden change in weather conditions.

To make the necessary temperature adjustments, you need to apply a scalar addition to both matrices. The scalar value represents the change in temperature, which can be positive or negative depending on whether it got warmer or cooler.

Your team observes a sudden drop in temperature, and you decide to adjust the data by subtracting 5 degrees Celsius or 9 degrees Fahrenheit

In [73]:
# Temperature data matrix in Celsius for a particular day (3 cities, 3 weather stations)
celsius_data = np.array([[25, 28, 31],
                         [22, 27, 30],
                         [20, 25, 28]])

# Temperature data matrix in Fahrenheit for the same day (3 cities, 3 weather stations)
fahrenheit_data = np.array([[77, 82.4, 87.8],
                            [71.6, 80.6, 86],
                            [68, 77, 82.4]])

# Display the original temperature data
print("Original Temperature Data (Celsius):")
print(celsius_data)

print("\nOriginal Temperature Data (Fahrenheit):")
print(fahrenheit_data)

# Scalar value for temperature adjustment (change in temperature)
celsius_adjustment = -5
fahrenheit_adjustment = -9

# Perform scalar addition for temperature adjustment
adjusted_celsius_data = celsius_data + celsius_adjustment
adjusted_fahrenheit_data = fahrenheit_data + fahrenheit_adjustment

print("\nAdjusted Temperature Data (Celsius):")
print(adjusted_celsius_data)

print("\nAdjusted Temperature Data (Fahrenheit):")
print(adjusted_fahrenheit_data)

Original Temperature Data (Celsius):
[[25 28 31]
 [22 27 30]
 [20 25 28]]

Original Temperature Data (Fahrenheit):
[[77.  82.4 87.8]
 [71.6 80.6 86. ]
 [68.  77.  82.4]]

Adjusted Temperature Data (Celsius):
[[20 23 26]
 [17 22 25]
 [15 20 23]]

Adjusted Temperature Data (Fahrenheit):
[[68.  73.4 78.8]
 [62.6 71.6 77. ]
 [59.  68.  73.4]]


# Scalar-Matrix Multiplication

Imagine you are a pricing analyst working for an e-commerce company that sells various products. The company decides to offer a limited-time discount on all products to attract more customers and boost sales. As a pricing analyst, you need to apply a discount to the prices of all products and calculate the new prices.

You have the original prices of the products stored in a 2x2 matrix, where each row represents a different product, and each column represents a different category of products (e.g., electronics, clothing). The matrix holds the original prices of each product in different categories.

Your company decides to offer a 20% discount on all products. To calculate the new discounted prices, you can perform scalar addition with a scalar value of 0.8 (1 - 0.2, representing a 20% discount).

In [74]:
# Original Prices of Products (2 products, 2 categories)
original_prices = np.array([[50, 30],
                            [100, 80]])

# Display the original prices
print("Original Prices:")
print(original_prices)

# Scalar value for discount (20% discount = 80% of original price)
discount = 0.8

# Perform scalar addition for discount
discounted_prices = discount * original_prices

print("\nDiscounted Prices:")
print(discounted_prices)

Original Prices:
[[ 50  30]
 [100  80]]

Discounted Prices:
[[40. 24.]
 [80. 64.]]


# Matrix-Matrix/Vector Multiplication

Imagine you are a data analyst working for a retail company that sells multiple products. The company records the daily sales quantities of different products and the corresponding prices for each product. To calculate the daily revenue generated from the sales of multiple products, you need to perform matrix-matrix multiplication.

The sales_quantities matrix holds the daily sales quantities of three products (Product A, Product B, and Product C) over three consecutive days. The product_prices matrix represents the prices of each product.

Now, you want to calculate the daily revenue generated from the sales of each product over the three days.

In [76]:
# Matrix of sales quantities (3 products, 5 days)
sales_quantities = np.array([[50, 40, 30],
                             [35, 45, 25],
                             [20, 30, 15]])

# Matrix of product prices (3 products, 1 column)
product_prices = np.array([[10],
                           [15],
                           [12]])
# Perform matrix-matrix multiplication to calculate revenue
daily_revenue = np.dot(sales_quantities, product_prices)

print("Matrix of Sales Quantities:")
print(sales_quantities)

print("\nMatrix of Product Prices:")
print(product_prices)

print("\nDaily Revenue:")
print(daily_revenue)

Matrix of Sales Quantities:
[[50 40 30]
 [35 45 25]
 [20 30 15]]

Matrix of Product Prices:
[[10]
 [15]
 [12]]

Daily Revenue:
[[1460]
 [1325]
 [ 830]]


# Matrix Transpose

Imagine you are a meteorologist working with a team to analyze temperature data from different cities. Your team collects temperature readings from various weather stations across four cities over the course of three days.

Now, let's say you need to analyze the data and work with the temperature data for each day separately. You can use matrix transpose to transform the data, so each row represents a different day, and each column represents a different city.

In [71]:
# Temperature data matrix (4 cities, 3 days)
temperature_data = np.array([[25, 28, 31],
                             [22, 27, 30],
                             [20, 25, 28],
                             [24, 26, 29]])

# Display the original temperature data
print("Original Temperature Data:")
print(temperature_data)

# Perform matrix transpose to analyze temperature data by day
temperature_data_transposed = np.transpose(temperature_data)

# Display the transposed temperature data
print("\nTransposed Temperature Data:")
print(temperature_data_transposed)

Original Temperature Data:
[[25 28 31]
 [22 27 30]
 [20 25 28]
 [24 26 29]]

Transposed Temperature Data:
[[25 22 20 24]
 [28 27 25 26]
 [31 30 28 29]]


# Matrix Determinant

Imagine you are a construction engineer working on a project to build a bridge across a river. As part of the project, you need to analyze the stability of the bridge's support structure. To do this, you need to calculate the determinant of a matrix representing the forces acting on different segments of the support structure.

You have identified three main segments of the bridge's support structure, and you need to calculate the determinant of the matrix representing the forces acting on these segments to ensure the stability of the bridge.

In [9]:
# Define the matrix of forces
forces_matrix = np.array([[10, 20, 50],
                          [600, 200, 400],
                          [500, 300, 100]])

# Calculate the determinant using np.linalg.det() function
determinant = np.linalg.det(forces_matrix)

print(determinant)

# Check the stability of the support structure
if determinant != 0:
    print("The support structure is stable under the applied forces.")
else:
    print("Warning: The support structure may not be stable under the applied forces. Consider adjustments or reinforcements.")

5800000.000000005
The support structure is stable under the applied forces.


# Matrix Inverse

## Calculating Inverse

In [29]:
# Define a 3x3 square matrix B
B = np.array([[100, 310, 240],
              [450, 620, 530],
              [780, 960, 850]])

# Calculate the inverse of matrix B using np.linalg.inv() function
B_inv = np.linalg.inv(B)

print("Matrix B:")
print(B)

print("Inverse of B:")
print(B_inv)

Matrix B:
[[100 310 240]
 [450 620 530]
 [780 960 850]]
Inverse of B:
[[-0.01847716  0.03360406 -0.01573604]
 [-0.03137056  0.10375635 -0.05583756]
 [ 0.05238579 -0.1480203   0.0786802 ]]


## Based on its Determinant

In [28]:
def is_invertible_by_determinant(matrix):
    # Calculate the determinant of the matrix
    determinant = np.linalg.det(matrix)

    # Check if the determinant is non-zero
    return not np.isclose(determinant, 0)

# Example usage:
matrix = np.array([[1, 2], [3, 4]])

invertible_by_determinant = is_invertible_by_determinant(matrix)
print("The matrix is invertible:", invertible_by_determinant)

The matrix is invertible: True


## Based on its Eigenvalues

In [22]:
def is_invertible_by_eigenvalues(matrix):
    # Calculate the eigenvalues of the matrix
    eigenvalues, _ = np.linalg.eig(matrix)

    # Check if all eigenvalues are non-zero
    return not np.any(np.isclose(eigenvalues, 0))

# Example usage:
matrix = np.array([[2, 3], [1, 4]])

invertible_by_eigenvalues = is_invertible_by_eigenvalues(matrix)
print("The matrix is invertible:", invertible_by_eigenvalues)

The matrix is invertible: True


## Based on its Rank

In [33]:
def is_invertible_by_rank(matrix):
    # Calculate the rank of the matrix
    rank = np.linalg.matrix_rank(matrix)
    num_rows, num_cols = matrix.shape

    # If the rank is less than the number of rows or columns, the matrix is not invertible
    return rank == num_rows and rank == num_cols

# Example usage:
matrix = np.array([[1, 3], [4, 2]])

invertible_by_rank = is_invertible_by_rank(matrix)
print("The matrix is invertible:", invertible_by_rank)

The matrix is invertible: True


## Based on its Row/Column operations

In [32]:
def is_invertible_by_row_column_ops(matrix):
    # Convert the matrix to its reduced row-echelon form (RREF)
    rref, _ = np.linalg.qr(matrix)

    # Check if the RREF is the identity matrix
    identity_matrix = np.eye(matrix.shape[0])
    return np.allclose(rref, identity_matrix)

# Example usage:
matrix = np.array([[1, 2], [3, 4]])

invertible_by_row_column_ops = is_invertible_by_row_column_ops(matrix)
print("The matrix is invertible:", invertible_by_row_column_ops)

The matrix is invertible: False


# Linearly Independent

## Based on rank

In [14]:
def are_vectors_linearly_independent(vectors):
    # Create a matrix from the vectors
    matrix = np.array(vectors)
    
    # Calculate the rank of the matrix
    rank = np.linalg.matrix_rank(matrix)
    
    # If rank equals the number of vectors, they are linearly independent
    return rank == len(vectors)

# Example: Forces on the Bridge
vectors = [
    [1000, 0, 0],   # Horizontal Force in Newtons
    [0, 500, 0],    # Vertical Force in Newtons
    [0, 0, 2000]    # Bending Moment in Newton-meters
]

result = are_vectors_linearly_independent(vectors)
print("Forces are linearly independent:", result)

Forces are linearly independent: True


## Based on Linear Combination and Trivial Solution

In [27]:
def are_linearly_independent(vectors):
    # Convert the list of vectors into a NumPy array
    vectors_array = np.array(vectors)
    
    # Check the shape of the array
    num_vectors, vector_dim = vectors_array.shape
    
    # Ensure there are at least as many vectors as their dimensions
    if num_vectors < vector_dim:
        return False

    # Solve the linear system using NumPy's linear algebra solver (np.linalg.solve)
    try:
        coefficients = np.linalg.solve(vectors_array, np.zeros(vector_dim))
    except np.linalg.LinAlgError:
        # If there's a LinAlgError, it means that the matrix is singular (linearly dependent)
        return False

    # Check if all coefficients are zero (trivial solution)
    return np.allclose(coefficients, 0)

# Example usage:
v1 = np.array([3, 1, 2])
v2 = np.array([6, 4, 5])
v3 = np.array([9, 7, 8])

vectors_set = [v1, v2, v3]
result = are_linearly_independent(vectors_set)
print("The vectors are linearly independent:", result)

The vectors are linearly independent: True


## Based on Determinant

In [26]:
def are_linearly_independent(vectors):
    # Convert the list of vectors into a NumPy array
    vectors_array = np.array(vectors)
    
    # Calculate the determinant of the matrix
    determinant = np.linalg.det(vectors_array)

    # Check if the determinant is non-zero
    return not np.isclose(determinant, 0)

# Example usage:
v1 = np.array([1, 2, 3])
v2 = np.array([4, 5, 6])
v3 = np.array([7, 8, 9])

vectors_set = [v1, v2, v3]
result = are_linearly_independent(vectors_set)
print("The vectors are linearly independent:", result)

The vectors are linearly independent: False


## Based on Null Space

In [25]:
def are_linearly_independent(vectors):
    # Convert the list of vectors into a NumPy array
    vectors_array = np.array(vectors)
    
    # Calculate the null space using NumPy's linear algebra solver (np.linalg.solve)
    null_space = np.linalg.solve(vectors_array, np.zeros(vectors_array.shape[1]))

    # Check if the null space contains only the zero vector
    return np.allclose(null_space, 0)

# Example usage:
v1 = np.array([2, 3, 1])
v2 = np.array([9, 7, 4])
v3 = np.array([5, 6, 8])

vectors_set = [v1, v2, v3]
result = are_linearly_independent(vectors_set)
print("The vectors are linearly independent:", result)

The vectors are linearly independent: True


## Based on Eigenvalues

In [24]:
def are_linearly_independent(vectors):
    # Convert the list of vectors into a NumPy array
    vectors_array = np.array(vectors)
    
    # Compute the eigenvalues of the matrix
    eigenvalues, _ = np.linalg.eig(vectors_array.T @ vectors_array)

    # Check if all eigenvalues are non-zero
    return np.all(np.abs(eigenvalues) > 1e-10)

# Example usage:
v1 = np.array([1, 2, 3])
v2 = np.array([4, 5, 6])
v3 = np.array([7, 8, 9])

vectors_set = [v1, v2, v3]
result = are_linearly_independent(vectors_set)
print("The vectors are linearly independent:", result)

The vectors are linearly independent: False


## Based on Row/Column Operations

In [23]:
def are_linearly_independent(vectors):
    # Convert the list of vectors into a NumPy array
    vectors_array = np.array(vectors)

    # Perform Gaussian elimination on the matrix
    rref, _ = np.linalg.qr(vectors_array)

    # Check if the echelon form has no rows of zeros
    if not np.any(np.all(rref == 0, axis=1)):
        return True

    # Check if the reduced row-echelon form is the identity matrix
    identity_matrix = np.eye(vectors_array.shape[1])
    return np.allclose(rref, identity_matrix)

# Example usage:
v1 = np.array([6, 1, 7])
v2 = np.array([4, 3, 8])
v3 = np.array([5, 2, 9])

vectors_set = [v1, v2, v3]
result = are_linearly_independent(vectors_set)
print("The vectors are linearly independent:", result)

The vectors are linearly independent: True
